import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:wolow/core/utils/anonymous_name.dart';

/// Parity gate: vectors in parity_vectors.json are generated by running the
/// REAL web implementation (src/lib/fun-anonymous-name.ts) in node. If these
/// fail, web and mobile would show different labels for the same conversation.
void main() {
  final vectors = jsonDecode(
    File('test/parity_vectors.json').readAsStringSync(),
  ) as Map<String, dynamic>;

  group('funAnonymousName parity with web', () {
    for (final entry in (vectors['names'] as List).cast<Map<String, dynamic>>()) {
      test('name/emoji for ${entry['id']}', () {
        expect(funAnonymousName(entry['id'] as String), entry['name']);
        expect(funAnonymousEmoji(entry['id'] as String), entry['emoji']);
      });
    }
  });

  group('nameInitials parity with web', () {
    for (final entry
        in (vectors['initials'] as List).cast<Map<String, dynamic>>()) {
      test('initials for "${entry['n']}"', () {
        expect(nameInitials(entry['n'] as String), entry['out']);
      });
    }
  });
}
