"use client";

/**
 * Tiny dependency-free confetti burst. The particle set is generated by the
 * caller (in an event handler, where impure randomness belongs) via
 * makeConfettiParticles(), then rendered as a fixed, non-interactive overlay
 * of brand-colored particles that fall, fade, and self-dismiss via onDone.
 * Under prefers-reduced-motion the factory returns no particles and the
 * component dismisses immediately.
 */

import { useEffect, useRef } from "react";

const COLORS = ["#7C3AED", "#EC4899", "#FB923C", "#FFFFFF", "#F9A8D4"];
const PARTICLE_COUNT = 26;
const MAX_LIFETIME_MS = 2000;

export type ConfettiParticle = {
  id: number;
  color: string;
  left: number; // starting horizontal position, vw %
  x: number; // horizontal drift, px
  y: number; // fall distance, px
  r: number; // total rotation, deg
  delay: number; // s
  duration: number; // s
  size: number; // px
  round: boolean;
};

/** Call from an event handler. Returns [] under prefers-reduced-motion. */
export function makeConfettiParticles(): ConfettiParticle[] {
  if (
    typeof window === "undefined" ||
    window.matchMedia("(prefers-reduced-motion: reduce)").matches
  ) {
    return [];
  }
  return Array.from({ length: PARTICLE_COUNT }, (_, i) => ({
    id: i,
    color: COLORS[i % COLORS.length],
    left: 15 + Math.random() * 70,
    x: (Math.random() - 0.5) * 240,
    y: 180 + Math.random() * 300,
    r: (Math.random() - 0.5) * 900,
    delay: Math.random() * 0.15,
    duration: 0.9 + Math.random() * 0.7,
    size: 6 + Math.random() * 6,
    round: Math.random() > 0.5,
  }));
}

export default function Confetti({
  particles,
  onDone,
}: {
  particles: ConfettiParticle[];
  onDone?: () => void;
}) {
  const empty = particles.length === 0;
  // Keep the latest onDone without retriggering the dismiss timer on
  // parent re-renders (callers pass inline closures).
  const onDoneRef = useRef(onDone);
  useEffect(() => {
    onDoneRef.current = onDone;
  }, [onDone]);

  useEffect(() => {
    const timer = window.setTimeout(() => onDoneRef.current?.(), empty ? 0 : MAX_LIFETIME_MS);
    return () => window.clearTimeout(timer);
  }, [empty]);

  if (empty) return null;

  return (
    <div className="pointer-events-none fixed inset-0 z-[60] overflow-hidden" aria-hidden="true">
      {particles.map((p) => (
        <span
          key={p.id}
          className="anim-confetti absolute top-[20%] block"
          style={
            {
              left: `${p.left}%`,
              width: `${p.size}px`,
              height: `${p.size * (p.round ? 1 : 0.6)}px`,
              backgroundColor: p.color,
              borderRadius: p.round ? "9999px" : "2px",
              "--confetti-x": `${p.x}px`,
              "--confetti-y": `${p.y}px`,
              "--confetti-r": `${p.r}deg`,
              "--confetti-delay": `${p.delay}s`,
              "--confetti-duration": `${p.duration}s`,
            } as React.CSSProperties
          }
        />
      ))}
    </div>
  );
}
